using System;
using System.Collections.Generic;
using System.IO;
using Dentogram.EurekahedgeParcing;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace DentogramTest
{
    [TestClass]
    public class EurekahedgeLockupParcerTest
    {
        private Tuple<string, string>[] samples = 
        {
            Tuple.Create("No", "; ; ; ;"),
            Tuple.Create("Yes (1 week)", "Hard; 1; Weeks; ;"),
            //Tuple.Create("Yes (Limit 10% per dealing day)", "Soft; 1; Days; 10;"),
            Tuple.Create("No (None)", "; ; ; ;"),
            Tuple.Create("No (1 year)", "Soft; 12; Months; ;"),
            Tuple.Create("No (Quarterly)", "Soft; 1; Months; ;"),
            Tuple.Create("Yes (Class A: 1 year  Class B: None)", "Hard; 12; Months; ;"),
            Tuple.Create("Yes", "Hard; ; ; ;"),
            //Tuple.Create("Yes (1 Year.  Early withdrawal subject to 5% penalty)", "Soft; 12; Months; 5;"),
            Tuple.Create("Yes (1 year  soft lock-up)", "Soft; 12; Months; ;"),
            Tuple.Create("No (Class B - 2 years  Class C - None)", "Soft; 24; Months; ;"),
            Tuple.Create("Yes (3 years & 1 year)", "Hard; 36; Months; ;"),
            Tuple.Create("Yes (4 quarter lock-up)", "Hard; 12; Months; ;"),
            Tuple.Create("Yes (1 year hard lock", "Hard; 12; Months; ;"),
            Tuple.Create("Yes (Annual)", "Hard; 1; Months; ;"),
            Tuple.Create("Yes (90 days initial lockup", "Hard; 90; Days; ;"),
            Tuple.Create("Yes (Soft lock after the 12 months)", "Soft; 12; Months; ;"),
            Tuple.Create("Yes (1 year  2 years  or 3 years)", "Hard; 12; Months; ;"),
            Tuple.Create("Yes (2-3 years)", "Hard; 36; Months; ;"),
            Tuple.Create("Yes (1 year soft lock up - 2%)", "Soft; 12; Months; 2;"),
            Tuple.Create("Yes (6 to 12 months)", "Hard; 12; Months; ;"),
            //Tuple.Create("Yes (12 months or 2% fee)", "Soft; 12; Months; 2;"),
            Tuple.Create("Yes (50days)", "Hard; 50; Days; ;"),
            Tuple.Create("Yes (2 years lock-up for Class B  3 years lock-up for Class C)", "Hard; 24; Months; ;"),
            Tuple.Create("Yes (December 31 of initial year of investment)", "Hard; ; ; ;"),
            Tuple.Create("Yes (1-year soft lock)", "Soft; 12; Months; ;"),
            Tuple.Create("Yes (1 yr for all for LPs admitted prior to Apr 1  2010)", "Hard; 12; Months; ;"),
            Tuple.Create("Yes (1 year (calendar year))", "Hard; 12; Months; ;"),
            Tuple.Create("Yes (Initial 3 years)", "Hard; 36; Months; ;"),
            Tuple.Create("Yes (soft lock)", "Soft; ; ; ;"),
            Tuple.Create("No (2% redemption for redeeming in first year)", "Soft; 12; Months; 2;"),
            Tuple.Create("Yes (monthly for Class A", "Hard; 1; Months; ;"),
            Tuple.Create("No (1% fee for withdrawals within the first 6 months)", "Soft; 6; Months; 1;"),
            //Tuple.Create("Yes (10% redemption limit per month)", "Soft; 1; Months; 10;"),
            Tuple.Create("Yes (2 years (until 30Jun07 and again from 1Jul07))", "Hard; 24; Months; ;"),
            Tuple.Create("Yes (2 years (from 1 May 2006))", "Hard; 24; Months; ;"),
            //Tuple.Create("No (20% gate)", "Soft; ; ; 20;"),
            //Tuple.Create("Yes (25% investor level gate)", "Soft; ; ; 25;"),
            Tuple.Create("Yes (Soft 1 year lock-up)", "Soft; 12; Months; ;"),
            Tuple.Create("Yes (1-year)", "Hard; 12; Months; ;"),
            //Tuple.Create("Yes (3% if redeemed within 1st year)", "Soft; 12; Months; 3;"),
            Tuple.Create("Yes (1-year on Class B", "Hard; 12; Months; ;"),
            //Tuple.Create("Yes (3% if redeemed within first 6 months)", "Soft; 6; Months; 3;"),
            Tuple.Create("Yes (Class 1 shares: 24 mths / Class 2 shares: 12 mths)", "Hard; 24; Months; ;"),
            Tuple.Create("Yes (1 year hard-lock)", "Hard; 12; Months; ;"),
            Tuple.Create("Yes (1 year", "Hard; 12; Months; ;"),
            Tuple.Create("No (No for Class A. Soft Lockup of 1 year for Class B)", "Soft; 12; Months; ;"),
            Tuple.Create("Yes (1 Year \"soft lock-up\")", "Soft; 12; Months; ;"),
            Tuple.Create("Yes (Soft lock up -1 year)", "Soft; 12; Months; ;"),
            Tuple.Create("Yes (Discretion of Manager)", "Hard; ; ; ;"),
            Tuple.Create("Yes (3-year or 5-year Fixed Term)", "Hard; 36; Months; ;"),
            Tuple.Create("Yes (1 or 3 years  depending on share class)", "Hard; 36; Months; ;"),
            Tuple.Create("Yes (1st 3 months for each investment made)", "Hard; 3; Months; ;"),
            Tuple.Create("Yes (1 yr soft for A  3 yrs hard for B - Institutional)", "Soft; 12; Months; ;"),
            Tuple.Create("Yes (Until 31st December 2007)", "Hard; ; ; ;"),
            //Tuple.Create("Yes (2 months with a 20%)", "Soft; 2; Months; 20;"),
            Tuple.Create("Yes (6 months from date of first investment)", "Hard; 6; Months; ;"),
            Tuple.Create("Yes (Class A/C - Nil / Class B/D - 3 years)", "Hard; 36; Months; ;"),
            Tuple.Create("Yes (12 months-hard and 12 to 18 months-soft)", "Hard; 12; Months; ;"),
            Tuple.Create("Yes (Optional with reduced fee for lock-up)", "Hard; ; ; ;"),
            Tuple.Create("Yes (3 year soft lock for quarterly class)", "Soft; 36; Months; ;"),
            Tuple.Create("Yes (60 days initial and 30 days thereafter)", "Hard; 60; Days; ;"),
            Tuple.Create("Yes (2 year with 90 day notice and 4 quarter payout)", "Hard; 24; Months; ;"),
            Tuple.Create("Yes (class A 3 years  class B 1 year)", "Hard; 36; Months; ;"),
            Tuple.Create("No (1 year from initial investment)", "Soft; 12; Months; ;"),
            Tuple.Create("Yes (2 year hard-lock  1 year soft)", "Hard; 24; Months; ;"),
            Tuple.Create("Yes (Soft 3 year lock)", "Soft; 36; Months; ;"),
            //Tuple.Create("Yes (5% between Year 1 and Year  2% thereafter)", "Soft; 12; Months; 5;"),
            Tuple.Create("Yes (Staggered liquidity during 1st 8 quarters)", "Hard; 24; Months; ;"),
            Tuple.Create("Yes (One-year hard lock-up.)", "Hard; 12; Months; ;"),
            //Tuple.Create("Yes (3% early redemption charge in 1st yr of investment)", "Soft; 12; Months; 3;"),
            Tuple.Create("Yes (1 year soft lock-up (1% early in redemption fee))", "Soft; 12; Months; 1;"),
            Tuple.Create("Yes (Soft lock-up: 1 year)", "Soft; 12; Months; ;"),
            Tuple.Create("Yes (Fixed income investors subject to 1-year lock-up)", "Hard; 12; Months; ;"),
            Tuple.Create("Yes (1st 6 months hard lock  2nd 6 months soft lock)", "Hard; 6; Months; ;"),
            Tuple.Create("No (Fees reduced with a 1 year lock-up)", "Soft; 12; Months; ;"),
            Tuple.Create("Yes (1 year soft lock-up with 3%)", "Soft; 12; Months; 3;"),
            Tuple.Create("Yes (1 year soft lock-up with 3% early redemption fee)", "Soft; 12; Months; 3;"),
            Tuple.Create("Yes (1 year from initial investment - A shares only)", "Hard; 12; Months; ;"),
            Tuple.Create("Yes (Soft Lock-up 2% penalty prior to 1 year)", "Soft; 12; Months; 2;"),
            Tuple.Create("Directors may limit redemptions of shares > 10%", "Soft; ; ; 10;"),
            Tuple.Create("Yes (6 months - original investment only)", "Hard; 6; Months; ;"),
            Tuple.Create("Yes (Class B: 12 months soft lock", "Soft; 12; Months; ;"),
            Tuple.Create("No (6 months soft lock)", "Soft; 6; Months; ;"),
            Tuple.Create("No (for Class 1", "; ; ; ;"),
            Tuple.Create("Yes (1 year soft lock from initial investment)", "Soft; 12; Months; ;"),
            //Tuple.Create("Yes (60 days - subject to 20% gate)", "Soft; 60; Days; 20;"),
            //Tuple.Create("Yes (10% in the first year", "Soft; 12; Months; 10;"),
            Tuple.Create("Yes (1 year rolling hard-lock)", "Hard; 12; Months; ;"),
            Tuple.Create("Yes (1st 2yrs firm lock-up", "Hard; 24; Months; ;"),
            //Tuple.Create("Yes (3% if redeemed in 1st year  1% next 12-24 mths)", "Soft; 12; Months; 3;"),
            Tuple.Create("Yes (3 months  thereafter monthly)", "Hard; 3; Months; ;"),
            //Tuple.Create("Yes (5% if redeemed prior to end of 6 month lock-up)", "Soft; 6; Months; 5;"),
            Tuple.Create("No (2-year soft-lock for the D-shares)", "Soft; 24; Months; ;"),
            Tuple.Create("Yes (Soft Lock-up  Redemption Charge 4.5% within 1st yr)", "Soft; 12; Months; ;"),
            Tuple.Create("Two year hard-lock", "Hard; 24; Months; ;"),
            Tuple.Create("Yes (Initial 1 year lock-up period)", "Hard; 12; Months; ;"),
            Tuple.Create("No (15% monthly gate)", "Soft; 1; Months; 15;"),
            Tuple.Create("No (but penalty if redeemed in one year)", "Soft; 12; Months; ;"),
            Tuple.Create("Yes (Soft lock-up for new investors)", "Soft; ; ; ;"),
            //Tuple.Create("Yes (1 year - 5%)", "Soft; 12; Months; 5;"),
            Tuple.Create("Yes (Soft lock-up after first 12 months)", "Soft; 12; Months; ;"),
            Tuple.Create("One year soft lock", "Soft; 12; Months; ;"),
            Tuple.Create("Yes (year 1 hard lock-up  year 2 & 3 soft lock-up)", "Hard; 12; Months; ;"),
            Tuple.Create("Yes (Soft Lock Up 1 Year)", "Soft; 12; Months; ;"),
            Tuple.Create("No (Soft lockup of 1 year)", "Soft; 12; Months; ;"),
            Tuple.Create("Yes (12 months hard lock  3% penalty in months 13-18)", "Hard; 12; Months; 3;"),
            Tuple.Create("Yes (12 month initial soft lock-up)", "Soft; 12; Months; ;"),
            //Tuple.Create("Yes (Early redemption: 3% 6 months", "Soft; 6; Months; 3;"),
            Tuple.Create("Yes (1 year soft lock-up/quarterly redemptions)", "Soft; 12; Months; ;"),
            //Tuple.Create("Yes (50% till year 2", "Soft; 24; Months; 50;"),
            Tuple.Create("Yes (2+ years)", "Hard; 24; Months; ;"),
            Tuple.Create("Yes (1 year or 2 year soft lock)", "Soft; 12; Months; ;"),
            Tuple.Create("Yes (Full exit in 2 Quarter with 45 day notice)", "Hard; 6; Months; ;"),
            Tuple.Create("Yes (Soft Lock-up (12 months))", "Soft; 12; Months; ;"),
            Tuple.Create("Yes (1 year  6 months rolling lock thereafter)", "Hard; 12; Months; ;"),
            Tuple.Create("No (No)", "; ; ; ;"),
            Tuple.Create("Yes (2 year hard and 1 year soft)", "Hard; 24; Months; ;"),
            Tuple.Create("Yes (Hard lock for the 1st year  soft-lock for 2nd year)", "Hard; 12; Months; ;"),
            Tuple.Create("Yes (3 months hard + 9 months soft)", "Hard; 3; Months; ;"),
            Tuple.Create("Yes (1 year soft", "Soft; 12; Months; ;"),
            Tuple.Create("Yes (2yr rolling)", "Hard; 24; Months; ;"),
            Tuple.Create("No (3% if redeemed in 1st year  1% next 12-24 mths)", "Soft; 12; Months; 3;"),
            Tuple.Create("No (3% in the first 12 months  1% next 12-24 months)", "Soft; 12; Months; 3;"),
            Tuple.Create("No (Soft-lock with 4% early redemption fee)", "Soft; ; ; 4;"),
            Tuple.Create("No (for Sub-Class 2 : 2-year hard lock-up ", "Hard; 24; Months; ;"),
            //Tuple.Create("Yes (Less than 6 months = 2%", "Soft; 6; Months; 2;"),
            Tuple.Create("Yes (Soft lock-up  5% 1st year", "Soft; 12; Months; 5;"),
            Tuple.Create("Yes (Hard lock-up)", "Hard; ; ; ;"),
            Tuple.Create("Yes (One year Soft lock(5% early redemption))", "Soft; 12; Months; 5;"),
            Tuple.Create("Soft Lock 18 months", "Soft; 18; Months; ;"),
            Tuple.Create("Yes (Annual Soft Lock)", "Soft; 1; Months; ;"),
            Tuple.Create("Yes (First 12 months)", "Hard; 12; Months; ;"),
            Tuple.Create("Yes (one year soft lock for Class 1", "Soft; 12; Months; ;"),
            Tuple.Create("Yes (1-year hard lock followed by 2-year soft lock)", "Hard; 12; Months; ;"),
            Tuple.Create("Yes (Class B: 2 years", "Hard; 24; Months; ;"),
            Tuple.Create("Yes (Hard lock up for seed investors only (3 years))", "Hard; 36; Months; ;"),
            Tuple.Create("Yes (2 years  1.5x volatility target drawdown trigger)", "Hard; 24; Months; ;"),
            Tuple.Create("Yes (12 months hard lock-up period)", "Hard; 12; Months; ;"),
            Tuple.Create("Not applicable", "; ; ; ;"),
            Tuple.Create("Yes (Hard lock-up 12 months)", "Hard; 12; Months; ;"),
            Tuple.Create("1 year", "Hard; 12; Months; ;"),
            Tuple.Create("Yes (5 years + 1 + 1  By the Board of Directors decision)", "Hard; 60; Months; ;"),
            Tuple.Create("Series A: 1yr", "Hard; 12; Months; ;"),
            Tuple.Create("Yes (Class A: No", "Hard; ; ; ;"),
            Tuple.Create("No (Only Class B shares have one-year lock-up)", "Soft; 12; Months; ;"),
            Tuple.Create("Yes (Rolling 1 Year Hard Lock)", "Hard; 12; Months; ;"),
            Tuple.Create("Yes (Soft lock-up  2% if redeemed within 6 calendar months  1% within 7th to 12th calendar months.)", "Soft; 6; Months; 2;"),
            //Tuple.Create("Yes (Redemption fee of 3% within 6 months lock up period)", "Soft; 6; Months; 3;"),
            Tuple.Create("Yes (2 years. In the interim investors may redeem up to 1/8 of their original investment each quarter.)", "Hard; 24; Months; ;"),
            Tuple.Create("6 month lock up", "Hard; 6; Months; ;"),
            Tuple.Create("Yes (2 years hard lock followed by quarterly redemptions thereafter or 1 year hard lock  followed by second year soft lock with 5% redemption penalty)", "Hard; 24; Months; 5;"),
            Tuple.Create("Yes (Alternatives range from 2 to 5 years)", "Hard; 60; Months; ;"),
            Tuple.Create("Yes (Six month soft lock (1%))", "Soft; 6; Months; 1;"),
            Tuple.Create("Yes (6 months soft lockup  4% redemption penalty)", "Soft; 6; Months; 4;"),
            Tuple.Create("Class A: no soft lock", "Soft; ; ; ;"),
            Tuple.Create("Yes (until January 2020)", "Hard; ; ; ;"),
            Tuple.Create("Yes (1 Year, soft lock)", "Soft; 12; Months; ;"),
            Tuple.Create("No (Closed until December 31, 2009)", "; ; ; ;"),
            Tuple.Create("Yes (1+ year from option tranche date)", "Hard; 12; Months; ;"),
            Tuple.Create("No (2% penalty in 1st yr for early redemption)", "Soft; 12; Months; 2;"),
            Tuple.Create("Yes (until 31 Dec 2006)", "Hard; ; ; ;"),
            Tuple.Create("Yes (Hard lockup of 36 months)", "Hard; 36; Months; ;"),
            Tuple.Create("Yes (3 years, extensible to 6 years)", "Hard; 36; Months; ;"),
            Tuple.Create("Yes (6 months hard, 6 months soft)", "Hard; 6; Months; ;"),
            //Tuple.Create("Yes (3 years, 15% may be redeemed on 2nd Anniversary)", "Soft; 36; Months; 15;"),
            Tuple.Create("Yes (1 year - soft)", "Soft; 12; Months; ;"),
            Tuple.Create("Yes (Year 1 soft with 4% redemption fee,  0% thereafter)", "Soft; 12; Months; 4;"),
            Tuple.Create("Yes (Each contribution subject to a one-year lockup", "Hard; 12; Months; ;"),
            Tuple.Create("Yes (2% before 12 months, 1% between 12 months and 24 months, 0% after 24 months)", "Hard; 12; Months; 2;"),
            Tuple.Create("Yes (1 year soft lock-up, 2% within the first 6 months and 1% subsequent 6 months)", "Soft; 12; Months; 2;"),
        };

        [TestMethod]
        public void Test()
        {
            var parcer = new EurekahedgeLockupParcer();
            

            Assert.AreEqual("Soft; 24; Months; 5;", parcer.Parce("Yes (1st 2yrs firm lock-up; soft lock-up of 5% exit fee)").ToTestString());
            Assert.AreEqual("Hard; 50; Days; ;", parcer.Parce("Yes (50days)").ToTestString());
            Assert.AreEqual("Hard; 6; Months; ;", parcer.Parce("Yes (six months)").ToTestString());
            Assert.AreEqual("Hard; 9; Months; ;", parcer.Parce("Yes (Nine months)").ToTestString());
            Assert.AreEqual("Hard; 12; Months; ;", parcer.Parce("Yes (year 1 hard lock-up  year 2 & 3 soft lock-up)").ToTestString());
            Assert.AreEqual("; ; ; ;", parcer.Parce("No (for Class A; Yes for Class B & C)").ToTestString());
            Assert.AreEqual("Hard; 12; Months; ;", parcer.Parce("Yes (Class A: No; Class B: Yes (1 year))").ToTestString());
            Assert.AreEqual("Soft; ; ; 4;", parcer.Parce("No (Soft-lock with 4% early redemption fee)").ToTestString());
            //Assert.AreEqual("Soft; 1; Months; 10;", parcer.Parce("Yes (10% redemption limit per month)").ToTestString());
            
            foreach (Tuple<string, string> sample in samples)
            {
                Assert.AreEqual(sample.Item2, parcer.Parce(sample.Item1).ToTestString());
            }
        }
    }
}
